#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 varanu5 <https://github.com/varanu5>
"""Generate the small font used for the setup network name."""
from pathlib import Path
from PIL import Image, ImageDraw
from gen_splash import load_font

font = load_font(20)
chars = ''.join(sorted(set('Tesserae-Setup-0123456789ABCDEF')))
lines = [
    '// Generated by tools/gen_setup_font.py.',
    '// SPDX-License-Identifier: AGPL-3.0-or-later',
    '#pragma once',
    '#include <stdint.h>',
    'static const struct { char ch; uint8_t advance; uint32_t rows[24]; } setup_glyphs[] = {'
]
for ch in chars:
    img = Image.new('1', (24, 24))
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=1)
    rows = [sum(img.getpixel((x, y)) << x for x in range(24)) for y in range(24)]
    advance = round(font.getlength(ch))
    lines.append("    {'%s', %d, {%s}}," % (ch, advance, ', '.join(hex(r) for r in rows)))
lines.append('};')
path = Path(__file__).resolve().parents[1] / 'firmware/main/setup_font.h'
path.write_text('\n'.join(lines) + '\n')
print(path)
