[platformio]
src_dir = main

[env:picpak]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = espidf
board = esp32-c3-devkitm-1
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 4194304
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions.csv
board_build.embed_files =
    main/assets/splash_setup.bin
    main/assets/splash_paired.bin
    main/assets/splash_lowbatt.bin
    main/assets/splash_revoked.bin
monitor_speed = 115200
